Football/Football/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/',include('accounts.urls')),
    path('matches/',include('matches.urls')),

]

Football/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns =[
    path('signup/',views.signup_view,name='signup_view'),
    path('login/',views.login_view,name='login_view'),
    path('logout/',views.logout_view,name='logout_view')
]

Football/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('',views.home_view,name='home_view'),
    path('mode/',views.theme_mode_view,name='theme_mode_view')
]

Football/matches/urls.py
from django.urls import path
from . import views

app_name = 'matches'

urlpatterns = [
    path('',views.matches_view,name='matches_view'),
    path('add_macth/',views.add_match_view,name='add_match_view'),
]

Football/main/models.py
from django.db import models

# Create your models here.


class League(models.Model):
    
    name = models.CharField(max_length=1024)
    len_clubs = models.SmallIntegerField(default=20)
    country = models.CharField(max_length=1024)
    

Football/matches/models.py
from django.db import models

# Create your models here.

Football/accounts/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest
from django.contrib.auth.models import User 
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
import random
from django.core.mail import send_mail
from django.conf import settings

def generate_verification_code():
    return str(random.randint(100000, 999999))


def send_verification_code_email(user_email,code):
    subject = 'Your Email Verification Code'
    message = f"Your verification code is: {code}"
    send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [user_email])
# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        try:
            new_user = User.objects.create_user(username=request.POST['username'],email=request.POST['email'],first_name=request.POST['first_name'],last_name=request.POST['last_name'],password=request.POST['password'])
            new_user.is_active = False
            new_user.save()
            verification_codes= {}
            code = generate_verification_code()
            verification_codes[new_user.email] = code
            send_verification_code_email(new_user.email, code)
            return render(request, "enter_code.html", {"email": new_user.email})
            
            
            
            messages.success(request,"user registered successfuly ","alert-success")
            return redirect('accounts:login_view')
    
        except Exception as e:
            messages.error(request,"user not registered, try again! ","alert-danger")
            print(e)
    return render(request,"accounts/signup.html")
def verfify_view(request):
    # to be continue .... 
    messages.success(request,"user registered successfuly ","alert-success")
    return redirect('accounts:login_view')
    return render(request,"accounts/signup.html")
    pass
def login_view(request:HttpRequest):
    if request.method == 'POST':
        user = authenticate(request, username=request.POST['username'],password=request.POST['password'])
        if user :
            login(request,user)
            messages.success(request,f"welome {user.username}, you logged in successfuly","alert-success")
            return redirect('main:home_view')
        else:
            messages.success(request,"no such user , try again !","alert-danger")
    return render(request,'accounts/login.html')

def logout_view(request):
    logout(request)
    messages.success(request,"logged out successfuly ", "alert-warning")
    return redirect('accounts:login_view')

Football/main/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest
# Create your views here.

def home_view(request):
    return render(request,'main/home.html')

def theme_mode_view(request:HttpRequest):
    referer = request.META.get('HTTP_REFERER', '/')
    response = redirect(referer)
    current_mode = request.COOKIES.get('dark_mode')
    
    if current_mode == 'true':
        response.set_cookie('dark_mode', 'false')
    else:
        response.set_cookie('dark_mode', 'true')
    return response

Football/matches/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from datetime import datetime
import requests
# Create your views here.
def add_match_view(request):
    if not request.user.is_staff:
        messages.success(request,"Only staff can access this page ", "alert-danger")
        return redirect('main:home_view')
    return render(request,'add_match.html')

def get_football_data():
    league_id = 2021
    month = 1 
    year = 2025
    url = f"https://api.football-data.org/v4/competitions/{league_id}/matches"
    
    headers = {
        "X-Auth-Token": "ec2876283a5743b783063d55e77ff97b"  # Replace with your actual API key
    }
    
    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        matches = response.json()['matches']
        
        filtered_matches = []
        
        for index,match in enumerate(matches):
            game = dict(match)
            if index == 0:
                print("type: " , type(match))
                for m in match:
                    print(f"type:{type(m)}: {m}")
                    print(f"value({type(match[m])}): {match[m]}")
            match_date = match['utcDate']
            date_obj = datetime.strptime(match_date, '%Y-%m-%dT%H:%M:%SZ')
            
            if date_obj.month == month and date_obj.year == year:
                home_team = match.get('homeTeam', {}).get('name', 'N/A')
                away_team = match.get('awayTeam', {}).get('name', 'N/A')
                score_home = match.get('score', {}).get('fullTime', {}).get('home', 'NA')
                score_away = match.get('score', {}).get('fullTime', {}).get('away', 'NA')
                home_crest = match.get('homeTeam',{}).get('crest',{})
                away_crest = match.get('awayTeam',{}).get('crest',{})
                match_date = date_obj.strftime('%Y-%m-%d')
                match_time = date_obj.strftime("%H:%M")
                filtered_matches.append({
                    'home_team': home_team,
                    'away_team': away_team,
                    'home_crest':home_crest,
                    'away_crest':away_crest,
                    'score_home': score_home,
                    'score_away': score_away,
                    'match_date': match_date,
                    'match_time':match_time,
                })
        return filtered_matches
    else:
        return []


def matches_view(request):
    matches = get_football_data() 
    league = "Premiur League" 
    return render(request, 'matches.html', {'league':league ,'matches': matches})

Football/accounts/templates/accounts/login.html
{%extends "main/base.html"%}
{%block title%} LOG IN {%endblock%}

{%block content%}
<div class="container d-flex flex-column justify-contact-center align-items-center">
    <h2 class="mb-3">Log in </h2>
    <form class="d-flex flex-column gap-3 w-50 " action="{%url 'accounts:login_view' %}" method="post" enctype="multipart/form-data">
        {%csrf_token%}

        <div class="form-floating">
            <input type="text" class="form-control" name="username" id="foatingInput" placeholder="username" required>
            <label for="floatingInput">username</label>
        </div>

        <div class="form-floating">
            <input type="password" class="form-control" name="password" id="foatingInput" placeholder="..." required >
            <label for="floatingInput">Password</label>
        </div>
        <div>
            <input type="submit" class="btn btn-primary w-100 py-2" value="log in" >
        </div>
    </form>
    <p>don't have an account ?  <a  href="{% url 'accounts:signup_view' %}">register here</a></p>

</div>
{%endblock%}

Football/accounts/templates/accounts/signup.html
{%extends "main/base.html"%}
{%block title%} SING UP {%endblock%}

{%block content%}
<div class="container d-flex flex-column justify-contact-center align-items-center">
    <h2>Sign up</h2>
    <form class="d-flex flex-column gap-3 w-50 " action="{%url 'accounts:signup_view' %}" method="post" enctype="multipart/form-data">
        {%csrf_token%}

        <div class="form-floating">
            <input type="email" class="form-control" name="email" id="foatingInput" placeholder="..."  required>
            <label for="floatingInput">Email address</label>
        </div>
        <div class="form-floating">
            <input type="text" class="form-control" name="username" id="foatingInput" placeholder="username" required>
            <label for="floatingInput">username</label>
        </div>
        <div class="form-floating">
            <input type="text" class="form-control" name="first_name" id="foatingInput" placeholder="first name" required>
            <label for="floatingInput">First Name</label>
        </div>
        <div class="form-floating">
            <input type="text" class="form-control" name="last_name" id="foatingInput" placeholder="last name"required >
            <label for="floatingInput">last Name</label>
        </div>
        <div class="form-floating">
            <input type="password" class="form-control" name="password" id="foatingInput" placeholder="..." required >
            <label for="floatingInput">Password</label>
        </div>
        <div>
            <input type="submit" class="btn btn-primary w-100 py-2" value="add user" >
        </div>
    </form>
</div>
{%endblock%}

Football/main/templates/main/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <link href="https://fonts.googleapis.com/css2?family=Bungee&family=Odibee+Sans&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <title>{%block title%}  BASE {%endblock%} </title>
</head>
<body class="{%if request.COOKIES.dark_mode == 'true' %}dark_mode{%endif%}">
    <header class="site-header">
      <nav class="navbar">
        <div class="navbar-brand">
          <a href="{%url 'main:home_view' %}">Fottball</a>
        </div>
        <div class="navbar-menu">
          <ul class="nav nav-pills">
            <li class= "mt-2">
              <div class="dropdown">
                {%if request.user.is_authenticated %}
                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{user.username}}
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{%url 'accounts:logout_view'%}">logout</a></li>
                </ul>
                {%else%}
                  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    register/login
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{%url 'accounts:signup_view' %}">register</a></li>
                    <li><a class="dropdown-item" href="{%url 'accounts:login_view'%}">log in</a></li>
                  </ul>
                {%endif%}
                
              </div>
            </li>
            <li class="nav-link ">
              <a href="{%url 'main:theme_mode_view' %}" class="material-symbols-outlined mt-1 nav-link">
              {%if request.COOKIES.dark_mode == 'true' %} light_mode {%else %} dark_mode {%endif%} </a>
            </li>
          {%if request.user.is_staff %}
            <li class="nav-link"><a href="{%url 'matches:add_match_view'%}" class="nav-link" aria-current="page">Add match</a></li>
          {%endif%}
          <li class="nav-link"><a href="#" class="nav-link">contact us</a></li>
          <li class="nav-link"><a href="{%url 'matches:matches_view' %}" class="nav-link active" style="background-color: var(--white-color);color:var(--text-color);">
            matches </a></li>
        </ul>
        </div>
      </nav>
    </header>
      <main class="container">
          {%if messages %}
            {%for message in messages %}
              <div class="alert {{message.tags}} alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {%endfor%}
          {%endif%}
            {%block content%}
            {%endblock%}
    </main>
    <footer class="site-footer">
      <p>&copy; {% now "Y" %} All rights reserved.</p>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

Football/main/templates/main/home.html
{% extends "main/base.html" %}

{%block title%}home page{%endblock%}

{%block content%}

<h1>this is the home page</h1>

{%endblock%}

Football/matches/templates/add_match.html
{%extends "main/base.html" %}

{%block title%} Add match page {%endblock%}

{%block content %}
    <h1>Add match</h1>
    <hr>
    <p>this page only for staff. </p>
{%endblock%}

Football/matches/templates/matches.html
{%extends "main/base.html" %}
    {%block title%}Premier League Matches{%endblock%}

    {%block content %}
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
        }
        th {
            background-color: #f4f4f4;
        }
    </style>
<body>
    <h1>Premier League Matches for March 2025</h1>

    {% if matches %}     
    <div class="d-flex flex-column gap-3 text-center p-3">
        {% for match in matches %}         
        {% {{}} %}        <div class="d-flex flex-column match-box p-3 rounded shadow-lg">
            <p class="text-muted"style="color: white !important;">{{ match.match_date }}</p>
            <div class="d-flex align-items-center text-center justify-content-between">
                <img class="team-logo mb-2" src="{{ match.home_crest }}" alt="{{ match.home_team }} crest">
                <h6 class="mb-2">  {{ match.home_team }}  </h6>
                <h4 class="shadow-3 fw-bold my-2">(<strong>{{match.score_home }}</strong>:<strong>{{ match.score_away }}</strong>)</h4>
                <h6>  {{ match.away_team }}  </h6>
                <img class="team-logo mb-2" src="{{ match.away_crest }}" alt="{{ match.away_team }} crest">
            </div>
            <p class="fw-bold my-2">{{match.match_time}}</p>

        </div>
        {% endfor %}
    </div>
    {% else %}
        <p class="alert alert-info text-center">No matches found for this month.</p>
    {% endif %}          
</body>
{%endblock%}